# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/inventory_foundation-sdk',
                'doc_host': 'https://d3group.github.io',
                'git_url': 'https://github.com/d3group/inventory_foundation-sdk',
                'lib_path': 'inventory_foundation_sdk'},
  'syms': {'inventory_foundation_sdk.core': {'inventory_foundation_sdk.core.foo': ('core.html#foo', 'inventory_foundation_sdk/core.py')}}}
